name: Update CSGO Cases Price

on:
  schedule:
    - cron: "*/20 * * * *" # Runs every 20 minutes
  workflow_dispatch:

jobs:
  update-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run check-price script
        id: check_price
        run: |
          npm run check-price > "CSGO Cases Price.txt"
        continue-on-error: true

      - name: Update Gist
        if: steps.check_price.outcome == 'success'
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_ACCESS_TOKEN }}
          gist_id: "5d424cb3223d34f121d8d68bdcf7fd07"
          file_path: "CSGO Cases Price.txt"
